# Generated by Django 3.1b1 on 2020-08-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('Ncelular', models.IntegerField()),
                ('fotogragia', models.ImageField(blank=True, null=True, upload_to='albums/images/')),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'unique_together': {('Ncelular',)},
            },
        ),
    ]
