# Generated by Django 3.1b1 on 2020-08-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('Ncelular', models.IntegerField()),
                ('fotogragia', models.ImageField(upload_to='albums/images/')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
