# Generated by Django 3.1b1 on 2020-08-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20200807_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fotogragia',
            field=models.ImageField(blank=True, null=True, upload_to='albums/images/'),
        ),
    ]
